model: fasterrcnn_resnet50_fpn_v2
data: data_configs/custom_data.yaml
device: cuda
epochs: 50
workers: 4
batch: 2
lr: 0.001
imgsz: 640
name: custom_training_50e_2b_resnet50_fpn_v_new
vis_transformed: false
mosaic: 0.0
use_train_aug: false
cosine_annealing: false
weights: null
resume_training: false
square_training: false
world_size: 1
dist_url: env://
disable_wandb: false
sync_bn: false
amp: false
seed: 0
project_dir: null
distributed: false
